export const foods = [
  {
    key: 'whiteRice',
    name: '白米饭',
    protein: 0.26,
    carbohydrate: 1.28,
    fat: 0.042857143,
    avatar: require('../../assets/images/food/white_rice.jpg'),
  },
  {
    key: 'brownRice',
    name: '糙米饭',
    protein: 0.296,
    carbohydrate: 1.544,
    fat: 0.045714286,
    avatar: require('../../assets/images/food/brown_rice.jpg'),
  },
  {
    key: 'friedSpinach',
    name: '炒菠菜',
    protein: 0.267,
    carbohydrate: 0.1935,
    fat: 0.177142857,
    avatar: require('../../assets/images/food/fried_spinach.jpg'),
  },
  {
    key: 'scallionDutchBeans',
    name: '葱油荷兰豆',
    protein: 0.272,
    carbohydrate: 0.249,
    fat: 0.428571429,
    avatar: require('../../assets/images/food/scallion_dutch_beans.jpg'),
  },
  {
    key: 'lowTemperatureLongliu',
    name: '低温龙利鱼块',
    protein: 0.12,
    carbohydrate: 0.03,
    fat: 0.171428571,
    avatar: require('../../assets/images/food/low_temperature_longliu.jpg'),
  },
  {
    key: 'redBeansRice',
    name: '红豆饭',
    protein: 0.348,
    carbohydrate: 1.2205,
    fat: 0.028571429,
    avatar: require('../../assets/images/food/red_beans_rice.jpg'),
  },
  {
    key: 'friedChickenBreast',
    name: '煎低温鸡胸',
    protein: 0.236,
    carbohydrate: 0,
    fat: 0.4,
    avatar: require('../../assets/images/food/fried_chicken_breast.jpg'),
  },
  {
    key: 'nuts',
    name: '每日坚果',
    protein: 0.32,
    carbohydrate: 0.235,
    fat: 1.514285714,
    avatar: require('../../assets/images/food/nuts.jpg'),
  },
  {
    key: 'friedPurpleCabbage',
    name: '清炒紫甘蓝',
    protein: 0.197,
    carbohydrate: 0.335,
    fat: 0.242857143,
    avatar: require('../../assets/images/food/fried_purple_cabbage.jpg'),
  },
  {
    key: 'saladDressing',
    name: '沙拉酱',
    protein: 0.28,
    carbohydrate: 0.68,
    fat: 5.5,
    avatar: require('../../assets/images/food/salad_dressing.jpg'),
  },
  {
    key: 'cabbage',
    name: '上汤奶白菜',
    protein: 0.335,
    carbohydrate: 0.073,
    fat: 0.195714286,
    avatar: require('../../assets/images/food/cabbage.jpg'),
  },
  {
    key: 'vegetableSalad',
    name: '蔬菜沙拉',
    protein: 0.118,
    carbohydrate: 0.27,
    fat: 0.197142857,
    avatar: require('../../assets/images/food/vegetable_salad.jpg'),
  },
  {
    key: 'garlicBroccoli',
    name: '蒜蓉西兰花',
    protein: 0.408,
    carbohydrate: 0.285,
    fat: 0.205714286,
    avatar: require('../../assets/images/food/garlic_broccoli.jpg'),
  },
  {
    key: 'carbonBarbecue',
    name: '碳烤肉',
    protein: 1.798,
    carbohydrate: 0.0925,
    fat: 1.251428571,
    avatar: require('../../assets/images/food/carbon_barbecue.jpg'),
  },
  {
    key: 'orangeDuckBreast',
    name: '香橙鸭胸',
    protein: 1.17,
    carbohydrate: 0.3145,
    fat: 0.188571429,
    avatar: require('../../assets/images/food/orange_duck_breast.jpg'),
  },
  {
    key: 'friedChicken',
    name: '炸鸡块',
    protein: 2.03,
    carbohydrate: 0.525,
    fat: 2.471428571,
    avatar: require('../../assets/images/food/fried_chicken.jpg'),
  },
  {
    key: 'cocaCola',
    name: '可口可乐',
    protein: 0,
    carbohydrate: 3.18,
    fat: 0,
    avatar: require('../../assets/images/food/coca_cola.jpg'),
  },
  {
    key: 'zeroCola',
    name: '零度可乐',
    protein: 0,
    carbohydrate: 0,
    fat: 0,
    avatar: require('../../assets/images/food/zero_cola.jpg'),
  },
  {
    key: 'dietCoke',
    name: '健怡可乐',
    protein: 0,
    carbohydrate: 0,
    fat: 0,
    avatar: require('../../assets/images/food/diet_coke.jpg'),
  },
  {
    key: 'sprite',
    name: '雪碧',
    protein: 0,
    carbohydrate: 2.75,
    fat: 0,
    avatar: require('../../assets/images/food/sprite.jpg'),
  },
  {
    key: 'minuteMaid',
    name: '果粒橙',
    protein: 0,
    carbohydrate: 2.1825,
    fat: 0,
    avatar: require('../../assets/images/food/minute_maid.jpg'),
  },
  {
    key: 'chunyueDrinkWater',
    name: '纯悦饮用水',
    protein: 0,
    carbohydrate: 0,
    fat: 0,
    avatar: require('../../assets/images/food/chunyue_drink_water.jpg'),
  },
]

export const MACRONUTRIENTS = [
  {
    key: 'carbohydrate',
    name: '碳水',
    value: 6,
  },
  {
    key: 'protein',
    name: '蛋白',
    value: 6,
  },
  {
    key: 'fat',
    name: '油脂',
    value: 6,
  },
]

export const MEAL_TIME = {
  BREAKFAST: '早餐',
  LUNCH: '午餐',
  DINNER: '晚餐',
}
