export const foods = [
  {
    key: 'whiteRice',
    name: '白米饭',
    protein: 0.182,
    carbohydrate: 0.896,
    fat: 0.03,
    avatar: require('../../assets/images/food/white_rice.jpg'),
  },
  {
    key: 'brownRice',
    name: '糙米饭',
    protein: 0.2072,
    carbohydrate: 1.0808,
    fat: 0.032,
    avatar: require('../../assets/images/food/brown_rice.jpg'),
  },
  {
    key: 'redBeansRice',
    name: '红豆饭',
    protein: 0.2436,
    carbohydrate: 0.85435,
    fat: 0.02,
    avatar: require('../../assets/images/food/red_beans_rice.jpg'),
  },
  {
    key: 'lowTemperatureLongliu',
    name: '低温龙利鱼块',
    protein: 2.034,
    carbohydrate: 0.027,
    fat: 0.154285714,
    avatar: require('../../assets/images/food/low_temperature_longliu.jpg'),
  },
  {
    key: 'friedChickenBreast',
    name: '煎低温鸡胸',
    protein: 1.77,
    carbohydrate: 0,
    fat: 0.3,
    avatar: require('../../assets/images/food/fried_chicken_breast.jpg'),
  },
  {
    key: 'carbonBarbecue',
    name: '碳烤肉',
    protein: 1.2586,
    carbohydrate: 0.06475,
    fat: 0.876,
    avatar: require('../../assets/images/food/carbon_barbecue.jpg'),
  },
  {
    key: 'orangeDuckBreast',
    name: '香橙鸭胸',
    protein: 0.819,
    carbohydrate: 0.22015,
    fat: 0.132,
    avatar: require('../../assets/images/food/orange_duck_breast.jpg'),
  },
  {
    key: 'friedChicken',
    name: '炸鸡块',
    protein: 1.827,
    carbohydrate: 0.4725,
    fat: 2.224285714,
    avatar: require('../../assets/images/food/fried_chicken.jpg'),
  },
  {
    key: 'friedSpinach',
    name: '炒菠菜',
    protein: 0.1869,
    carbohydrate: 0.13545,
    fat: 0.124,
    avatar: require('../../assets/images/food/fried_spinach.jpg'),
  },
  {
    key: 'scallionDutchBeans',
    name: '葱油荷兰豆',
    protein: 0.2176,
    carbohydrate: 0.1992,
    fat: 0.342857143,
    avatar: require('../../assets/images/food/scallion_dutch_beans.jpg'),
  },
  {
    key: 'friedPurpleCabbage',
    name: '清炒紫甘蓝',
    protein: 0.1379,
    carbohydrate: 0.2345,
    fat: 0.17,
    avatar: require('../../assets/images/food/fried_purple_cabbage.jpg'),
  },
  {
    key: 'cabbage',
    name: '上汤奶白菜',
    protein: 0.3685,
    carbohydrate: 0.0803,
    fat: 0.215285714,
    avatar: require('../../assets/images/food/cabbage.jpg'),
  },
  {
    key: 'garlicBroccoli',
    name: '蒜蓉西兰花',
    protein: 0.2856,
    carbohydrate: 0.1995,
    fat: 0.144,
    avatar: require('../../assets/images/food/garlic_broccoli.jpg'),
  },
  {
    key: 'vegetableSalad',
    name: '蔬菜沙拉',
    protein: 0.0826,
    carbohydrate: 0.189,
    fat: 0.138,
    avatar: require('../../assets/images/food/vegetable_salad.jpg'),
  },
  {
    key: 'saladDressing',
    name: '沙拉酱',
    protein: 0.014,
    carbohydrate: 0.034,
    fat: 0.275,
    avatar: require('../../assets/images/food/salad_dressing.jpg'),
  },
  {
    key: 'cocaCola',
    name: '可口可乐 600ml',
    protein: 0,
    carbohydrate: 3.18,
    fat: 0,
    avatar: require('../../assets/images/food/coca_cola.jpg'),
  },
  {
    key: 'zeroCola',
    name: '零度可乐 500ml',
    protein: 0,
    carbohydrate: 0,
    fat: 0,
    avatar: require('../../assets/images/food/zero_cola.jpg'),
  },
  {
    key: 'dietCoke',
    name: '健怡可乐 500ml',
    protein: 0,
    carbohydrate: 0,
    fat: 0,
    avatar: require('../../assets/images/food/diet_coke.jpg'),
  },
  {
    key: 'sprite',
    name: '雪碧 600ml',
    protein: 0,
    carbohydrate: 3.3,
    fat: 0,
    avatar: require('../../assets/images/food/sprite.jpg'),
  },
  {
    key: 'minuteMaid',
    name: '果粒橙 450ml',
    protein: 0,
    carbohydrate: 2.1825,
    fat: 0,
    avatar: require('../../assets/images/food/minute_maid.jpg'),
  },
  {
    key: 'chunyueDrinkWater',
    name: '纯悦饮用水 550ml',
    protein: 0,
    carbohydrate: 0,
    fat: 0,
    avatar: require('../../assets/images/food/chunyue_drink_water.jpg'),
  },
  {
    key: 'nuts',
    name: '每日坚果',
    protein: 0.08,
    carbohydrate: 0.05875,
    fat: 0.378571429,
    avatar: require('../../assets/images/food/nuts.jpg'),
  },
]

export const MACRONUTRIENTS = [
  {
    key: 'carbohydrate',
    name: '碳水',
    value: 6,
  },
  {
    key: 'protein',
    name: '蛋白',
    value: 6,
  },
  {
    key: 'fat',
    name: '油脂',
    value: 6,
  },
]

export const MEAL_TIME = {
  BREAKFAST: '早餐',
  LUNCH: '午餐',
  DINNER: '晚餐',
}
